---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
    attributes:
      postgres:
        version: "9.3"
  - name: centos-6.5
    run_list:
      - recipe[yum]

suites:
  - name: default
    data_bags_path: data_bags
    run_list:
      - recipe[supermarket::default]
    attributes:
      postgres:
        auth_method: trust
