---
driver:
  name: vagrant

driver_config:
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]
  - ["private_network", {ip: "33.33.33.10"}]
  customize:
    memory: 2024
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
      - recipe[yum]

suites:
  - name: default
    data_bags_path: data_bags
    run_list:
      - recipe[supermarket::default]
    attributes:

