---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
  driver_plugin: digital_ocean
  driver_config:
    size: 4gb
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-14.04
  driver_plugin: digital_ocean
  driver_config:
    size: 4gb
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    attributes:
      postgres:
        version: "9.3"
  run_list:
  - recipe[apt]

- name: centos-6.5
  driver_plugin: digital_ocean
  driver_config:
    size: 4gb
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>

suites:
  - name: default
    data_bags_path: data_bags
    run_list:
      - recipe[supermarket::default]
    attributes:
      postgres:
        auth_method: trust
  - name: force_ssl
    data_bags_path: data_bags
    run_list:
      - recipe[supermarket::default]
    attributes:
      postgres:
        auth_method: trust
      supermarket:
        force_ssl: true
        allow_http_domain:
          - 'http-only.example.com'
  - name: supermarket_instance
    run_list:
      - recipe[supermarket_instance_test::default]
    attributes: {}
