source 'https://supermarket.getchef.com'

metadata

cookbook 'redis', git: 'https://github.com/meanbee/chef-redis.git'
cookbook 'bluepill', git: 'https://github.com/opscode-cookbooks/bluepill.git'
cookbook 'rsyslog', git: 'https://github.com/opscode-cookbooks/rsyslog.git'
cookbook 'ohai', git: 'https://github.com/opscode-cookbooks/ohai.git'
cookbook 'nginx', git: 'https://github.com/miketheman/nginx.git'
cookbook 'ruby_install', git: 'https://github.com/rosstimson/chef-ruby_install.git'
cookbook 'chruby_install', git: 'https://github.com/ichilton/chef_chruby_install.git'
cookbook 'rubies', git: 'https://github.com/stephenlauck/chef_rubies.git', ref: 'add_version_attr_for_bundler'
cookbook 'rubies', git: 'https://github.com/ichilton/chef_rubies.git'
cookbook 'python', git: 'https://github.com/poise/python.git'
cookbook 'nodejs', git: 'https://github.com/redguide/nodejs.git'
cookbook 'ark', git: 'https://github.com/burtlo/ark.git'
cookbook 'postgresql', git: 'https://github.com/stephenlauck/postgresql.git'
cookbook 'git', git: 'https://github.com/jssjr/git.git'
cookbook '7-zip', git: 'https://github.com/sneal/7-zip.git'
cookbook 'openssl', git: 'https://github.com/opscode-cookbooks/openssl.git'
cookbook 'dmg', git: 'https://github.com/opscode-cookbooks/dmg.git'
cookbook 'chef-sugar', git: 'https://github.com/sethvargo/chef-sugar.git'
